-- DDI owns this schema. Apply explicitly with the deployment migration runner.
-- Startup never creates, resets, drops, or seeds production state.
CREATE TABLE IF NOT EXISTS ddi_infrastructures (id TEXT PRIMARY KEY, owner_subject TEXT NOT NULL, type TEXT NOT NULL, status TEXT NOT NULL, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS ddi_applications (id TEXT PRIMARY KEY, infrastructure_id TEXT NOT NULL REFERENCES ddi_infrastructures(id), type TEXT NOT NULL, display_name TEXT NOT NULL, public_url TEXT, admin_url TEXT, status TEXT NOT NULL, requested_capabilities JSONB NOT NULL, granted_capabilities JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS ddi_primitive_bindings (id TEXT PRIMARY KEY, infrastructure_id TEXT NOT NULL REFERENCES ddi_infrastructures(id), namespace TEXT NOT NULL, provider TEXT NOT NULL, configured BOOLEAN NOT NULL, provider_reference TEXT, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS ddi_relationships (id TEXT PRIMARY KEY, source TEXT NOT NULL, target TEXT NOT NULL, relationship_type TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'ACTIVE', metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS ddi_audits (id UUID PRIMARY KEY, correlation_id TEXT NOT NULL, infrastructure_id TEXT NOT NULL, application_id TEXT, actor_subject TEXT, audience TEXT NOT NULL, capability TEXT NOT NULL, action TEXT NOT NULL, resource TEXT NOT NULL, provider TEXT, grant_id TEXT, decision TEXT NOT NULL, reason TEXT, execution_mode TEXT NOT NULL, result TEXT NOT NULL, timestamp TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS ddi_idempotency (key TEXT PRIMARY KEY, owner_subject TEXT NOT NULL, response JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL);
CREATE INDEX IF NOT EXISTS ddi_audits_infra_timestamp_idx ON ddi_audits (infrastructure_id, timestamp DESC);
